# checkpoint: /proj/rep-learning-robotics/users/x_yufdu/daxia/diffusion/diffusion_policy/data/outputs/___default100100/checkpoints/epoch=1650-test_mean_score=0.723.ckpt
# checkpoint: /proj/rep-learning-robotics/users/x_yufdu/daxia/diffusion/realtime_dp/diffusion_policy/data/dp_cp/pusht_image/epoch=1850-test_mean_score=0.898.ckpt
checkpoint: /proj/rep-learning-robotics/users/x_yufdu/daxia/diffusion/realtime_dp/diffusion_policy/data/dp_cp/can_mh_image/cp.ckpt
output_path: data/nt/lift_ph_lowdim/grip_scale_10_rti${now:%Y.%m.%d-%H.%M.%S}
output_dir: ${output_path}/${now:%Y.%m.%d-%H.%M.%S}
n_action_steps: 1
_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_rti_workspace.TrainDiffusionUnetHybridRTIWorkspace
requires_grad: True
# steps: [2,1,0]

policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_rti_policy.DiffusionUnetHybridImageRTIPolicy
  steps: [40,35,30,25,20,17,15,12,10,8,5,3,2,1,0]
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100

