checkpoint: data/rti-dp-scale/square_lowdim/train_0/cp1.ckpt
output_path: data/result/lowdim/square_scale/
output_dir: ${output_path}/${now:%Y.%m.%d-%H.%M.%S}
n_action_steps: 1
_target_: diffusion_policy.workspace.train_diffusion_unet_lowdim_rti_workspace.TrainDiffusionUnetLowdimRTIWorkspace

policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_rti_policy.DiffusionUnetLowdimRTIPolicy
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
  steps: [15,13,11,9,7,5,3,2,1,0]
  discrete_action:
    has_discrete_action: true
    scale: true
    factor: 1.0