checkpoint: /proj/rep-learning-robotics/users/x_yufdu/daxia/diffusion/realtime_dp/diffusion_policy/data/dp_cp/pusht_image/cp2.ckpt
output_path: data/rti/release/image/pusht/
output_dir: ${output_path}/${now:%Y.%m.%d-%H.%M.%S}
n_action_steps: 1
_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_rti_workspace.TrainDiffusionUnetHybridRTIWorkspace

policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_rti_policy.DiffusionUnetHybridImageRTIPolicy
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
  steps: [15,13,11,9,7,5,3,2,1,0]
  discrete_action:
    has_discrete_action: true
    scale: false
    factor: 10.0