checkpoint: data/dp_cp/pusht_image/cp1.ckpt
output_path: data/result/image/pusht/
output_dir: ${output_path}/${now:%Y.%m.%d-%H.%M.%S}
n_action_steps: 1
_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_rti_workspace.TrainDiffusionUnetHybridRTIWorkspace

policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_rti_policy.DiffusionUnetHybridImageRTIPolicy
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
  steps: [3,1,0]
  discrete_action:
    has_discrete_action: false
    scale: false
    factor: 1.0

