checkpoint: data/rti-dp-scale/th_image/train_0/cp1.ckpt
output_path: data/result/image/th_scale/
output_dir: ${output_path}/${now:%Y.%m.%d-%H.%M.%S}
n_action_steps: 1
_target_: diffusion_policy.workspace.train_diffusion_unet_hybrid_rti_workspace.TrainDiffusionUnetHybridRTIWorkspace

policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_rti_policy.DiffusionUnetHybridImageRTIPolicy
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    num_train_timesteps: 100
  steps: [5,3,1,0]
  discrete_action:
    has_discrete_action: true
    scale: true
    factor: 10.0
